### ISSUE TITLE
Motor class constructor parameter change

### ISSUE THREAD

**Issue by KevinMatthewFox** [KevinMatthewFox/welcome-to-the-SLAM#1]
Hey ryan, just wondering why you changed the motor constructor to no longer take in the pwm and gpio controllers?

instead of
Motor(const int pwnPinNum, PwmController ^pwmController, double dutyCycle, GpioController ^gpio, const int inA, const int inB, const int enA, const int enB);

it's now
Motor(const int pwnPinNum,  double dutyCycle,  const int inAPin, const int inBPin, const int enAPin, const int enBPin)

I saw you added the
PwmController ^pwmController;
GpioController ^gpio;

to the function but isn't that basically the same as passing them as parameters, except use more memory?

but if we already have those declared in main, why do we need them in that function? 
I also think that if we do decide to do the code that way, we need to use initialize the gpio controller within that function as well (something like gpio = GpioController::getDefault();)

**Comment by ryanwang92** [comment]
Hey Kevin:

The reason why I do it in my way is that I do not figure out how to pass
the parameter for PwmController ^pwmController and GpioController ^gpio,
and I avoid that problem by another way which is written in the code.
However, I believe we still need to declare the PwmController
^pwmController and GpioController ^gpio inside our function because they
are being used as variables, and we should include our initialization for
them like what you said.

On Mon, Feb 29, 2016 at 6:09 PM, Kevin Fox notifications@github.com wrote:

> Hey ryan, just wondering why you changed the motor constructor to no
> longer take in the pwm and gpio controllers?
> 
> instead of
> Motor(const int pwnPinNum, PwmController ^pwmController, double dutyCycle,
> GpioController ^gpio, const int inA, const int inB, const int enA, const
> int enB);
> 
> it's now
> Motor(const int pwnPinNum, double dutyCycle, const int inAPin, const int
> inBPin, const int enAPin, const int enBPin)
> 
> I saw you added the
> PwmController ^pwmController;
> GpioController ^gpio;
> 
> to the function but isn't that basically the same as passing them as
> parameters, except use more memory?
> 
> but if we already have those declared in main, why do we need them in that
> function?
> I also think that if we do decide to do the code that way, we need to use
> initialize the gpio controller within that function as well (something like
> gpio = GpioController::getDefault();)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KevinMatthewFox/welcome-to-the-SLAM/issues/1.

## 

Jiaxiang Wang
Electrical Engineering Undergraduate
Engineering Ambassador
